---
#
# Ansible managed
#
repository:
  description: Install and configure terraform on your system.
  homepage: https://buluma.github.io/
  topics: terraform, ansible, molecule, tox, playbook, hacktoberfest
