---
image: "buluma/github-action-molecule:5.0.0"

# services:
#   - docker:dind
#
# variables:
#   DOCKER_HOST: "tcp://docker:2375"
#   PY_COLORS: 1

variables:
  PY_COLORS: 1

molecule:
  script:
    - if [ -f tox.ini ] ; then tox ; fi
    - if [ ! -f tox.ini ] ; then molecule test ; fi
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  retry: 1
  parallel:
    matrix:
      - image: "alpine-openrc"
        tag: "latest"
      - image: "amazonlinux"
        tag: "latest"
      - image: "enterpriselinux"
        tag: "8"
      - image: "debian-systemd"
        tag: "latest"
      - image: "debian-systemd"
        tag: "buster"
      - image: "fedora-systemd"
        tag: "35"
      - image: "fedora-systemd"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "rawhide"
      - image: "docker-opensuse-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"
      - image: "docker-ubuntu-systemd"
        tag: "jammy"

galaxy:
  script:
    - ansible-galaxy role import --api-key ${GALAXY_API_KEY} ${CI_PROJECT_NAMESPACE} ${CI_PROJECT_NAME}
  rules:
    - if: $CI_COMMIT_TAG != null
